spring.application.name=auction

spring.datasource.url=jdbc:postgresql://localhost:5432/auction
spring.datasource.username=postgres
spring.datasource.password=123456


spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.repositories.enabled=true

# JWT
app.jwtSecret=MysuperreliableandexcellentJWTsecretfortheperfectprojectandtheperfectprogrammerswhowroteit
app.jwtExpirationMs=600000

# Логи 
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.project.auction=DEBUG
logging.file.name=logs/app.log
