spring.application.name=auction

spring.datasource.url=jdbc:postgresql://localhost:5432/auction
spring.datasource.username=postgres
spring.datasource.password=123456


spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.repositories.enabled=true

# JWT
app.jwtSecret=MysuperreliableandexcellentJWTsecretfortheperfectprojectandtheperfectprogrammerswhowroteit
app.jwtExpirationMs=600000

# Логи 
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.project.auction=DEBUG
logging.file.name=logs/app.log
# почта надо подставить реальные значения хоста, порта, логина и пароля почтового сервера
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your_login
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
